//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSP
    {
        public PhanLoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaPhanLoai { get; set; }
        public string TenPhanLoai { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
